//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Popa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Popa()
        {
            this.Таблица21 = new HashSet<Таблица2>();
        }
    
        public int Lupa { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> ID_Pupa { get; set; }
    
        public virtual Таблица2 Таблица2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Таблица2> Таблица21 { get; set; }
    }
}
