//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImgTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Таблица2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Таблица2()
        {
            this.Popa = new HashSet<Popa>();
        }
    
        public int ID_Pupa { get; set; }
        public Nullable<int> ID_Lupa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Popa> Popa { get; set; }
        public virtual Popa Popa1 { get; set; }
    }
}
